global.ALIVE_TICKS = 150;
global.UPDATE_INTERVAL_STRUCTURES = 200;
global.UPDATE_INTERVAL_RESOURCES = 1;
global.UPDATE_INTERVAL_PATHCACHE = 1000;
global.UPDATE_INTERVAL_BALANCE = 500;
global.ROADS_TIMEOUT = 1500;
global.ROADS_REPAIR_WANTED = 5;
global.ROADS_CONSTRUCT_WANTED = 30;
global.REPAIR_TOWER_LIMIT = 10000;
global.REPAIR_LIMIT = 5000000;
global.REPAIR_LIMIT_HIGH = 100000000;
global.REPAIR_ENERGY_LIMIT = 300000;
global.MAX_ENERGY_BY_LONGHARVEST = 500000;
global.STRUCTURE_SOURCE = "source";
global.ENERGY_TIMEOUT = 100;
global.PERIOD_MEMORY = 10;
global.PERIOD_NEEDLIST = 10;
global.PATH_TIMEOUT = 4;
global.PATH_OPS_LIMIT_LONG = 10000;
global.PATH_OPS_LIMIT_SHORT = 200;
global.PATH_OPS_LIMIT_ROOM = 2000;
global.PATHCACHE_USE_TIMEOUT = 2000;
global.PATHCACHE_CREATE_TIMEOUT = 5000;
global.HOSTILES_DEAD_TIMEOUT = 200;
global.UPGRADERS_EXTRA_ENERGY = 50000;
global.MAX_CONSTRUCTIONS_PER_ROOM = 10;
global.ARMY_MIN_FRIENDS = 1;
global.ARMY_MIN_HEALERS = 1;
global.TRANSPORT_REQUEST_TIMEOUT = 10000;
global.TRANSPORTER_STRUCTURES_INTERVAL = 500;
global.TRANSPORTER_MIN_CONTAINER_AMOUNT = 1000;
global.TRANSPORTER_CREATING_AMOUNT = 4000;
global.MERGE_TRANSPORT_AMOUNT = 1000;
global.MIN_RES_AMOUNT = 10000;
global.MIN_RES_SELLING_AMOUNT = 1000;
global.MIN_TERMINAL_ENERGY = 10000;
global.LAB_REQUEST_AMOUNT = 3000;
global.LAB_TRANSPORT_AMOUNT = 1000;
global.MINERALMINER_CARRY_LIMIT = 100;
global.KEEPLAIR_LEAVE_TIME = 10;
global.SUPER_HEALER_MINCOUNT = 3;
global.BALANCE_MIN = 10000;
global.BALANCE_MAX = 20000;
global.BALANCE_LAB_MIN = 500;
global.BALANCE_TRANSPORT_MIN = 1000;
global.BOOST_MIN_TICKS = 1200;
global.BOOST_STOP_TICKS = 900;
global.BOOST_BUILDER_MIN_BTICKS = 20000;
global.CREEP_WEIGHT = {
    defender: 1,
    antikeeper: 1,
    miner: 2,
    longminer: 2,
    superattacker: 3,
    superhealer: 3,
    mineralminer: 4,
    harvester: 5,

    default: 10,
};