global.ALIVE_TICKS = 200;
global.UPDATE_INTERVAL_STRUCTURES = 100;
global.UPDATE_INTERVAL_HOSTILES = 2;
global.ROADS_TIMEOUT = 1500;
global.ROADS_REPAIR_WANTED = 5;
global.ROADS_CONSTRUCT_WANTED = 30;
global.REPAIR_LIMIT = 2500000;